# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'app.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(418, 127)
        MainWindow.setMinimumSize(QtCore.QSize(418, 127))
        MainWindow.setMaximumSize(QtCore.QSize(418, 127))
        MainWindow.setStyleSheet("QMainWindow {\n"
"background-color: #fff;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.topContainerFrame = QtWidgets.QFrame(self.centralwidget)
        self.topContainerFrame.setStyleSheet("background-color: #fff;")
        self.topContainerFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.topContainerFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.topContainerFrame.setObjectName("topContainerFrame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.topContainerFrame)
        self.horizontalLayout.setContentsMargins(2, 2, 2, 2)
        self.horizontalLayout.setSpacing(2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.topControlsFrame = QtWidgets.QFrame(self.topContainerFrame)
        self.topControlsFrame.setStyleSheet("background-color: #fff;")
        self.topControlsFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.topControlsFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.topControlsFrame.setObjectName("topControlsFrame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.topControlsFrame)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.recordPushButton = QtWidgets.QPushButton(self.topControlsFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.recordPushButton.sizePolicy().hasHeightForWidth())
        self.recordPushButton.setSizePolicy(sizePolicy)
        self.recordPushButton.setMaximumSize(QtCore.QSize(130, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.recordPushButton.setFont(font)
        self.recordPushButton.setStyleSheet("QPushButton#recordPushButton {\n"
"background-color: #000;\n"
"border: none;\n"
"outline: none;\n"
"border-radius: 8px;\n"
"color: #fff;\n"
"padding: 17px 10px;\n"
"}\n"
"\n"
"QPushButton#recordPushButton:hover {\n"
"    background-color: #121212;\n"
"}\n"
"\n"
"QPushButton#recordPushButton:pressed {\n"
"    background-color: #1f1f1f;\n"
"}")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/record_circle.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.recordPushButton.setIcon(icon)
        self.recordPushButton.setIconSize(QtCore.QSize(15, 15))
        self.recordPushButton.setObjectName("recordPushButton")
        self.horizontalLayout_2.addWidget(self.recordPushButton)
        self.timeQLabel = QtWidgets.QLabel(self.topControlsFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.timeQLabel.sizePolicy().hasHeightForWidth())
        self.timeQLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(11)
        self.timeQLabel.setFont(font)
        self.timeQLabel.setStyleSheet("QLabel {\n"
"color: #9DA4AA;\n"
"}")
        self.timeQLabel.setObjectName("timeQLabel")
        self.horizontalLayout_2.addWidget(self.timeQLabel)
        self.horizontalLayout.addWidget(self.topControlsFrame)
        self.folderFrame = QtWidgets.QFrame(self.topContainerFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.folderFrame.sizePolicy().hasHeightForWidth())
        self.folderFrame.setSizePolicy(sizePolicy)
        self.folderFrame.setStyleSheet("background-color: #fff;")
        self.folderFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.folderFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.folderFrame.setObjectName("folderFrame")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.folderFrame)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.folderPushButton = QtWidgets.QPushButton(self.folderFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.folderPushButton.sizePolicy().hasHeightForWidth())
        self.folderPushButton.setSizePolicy(sizePolicy)
        self.folderPushButton.setStyleSheet("QPushButton#folderPushButton {\n"
"    background-color: #fff;\n"
"    outline: none;\n"
"    border: none;\n"
"    border-radius: 8px;\n"
"    padding: 17px 4px;\n"
"}\n"
"\n"
"QPushButton#folderPushButton:hover {\n"
"    background-color: #f9f9f9;\n"
"}\n"
"\n"
"QPushButton#folderPushButton:pressed {\n"
"    background-color: #f7f7f7;\n"
"}")
        self.folderPushButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icons/folder.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.folderPushButton.setIcon(icon1)
        self.folderPushButton.setIconSize(QtCore.QSize(40, 24))
        self.folderPushButton.setObjectName("folderPushButton")
        self.horizontalLayout_3.addWidget(self.folderPushButton)
        self.horizontalLayout.addWidget(self.folderFrame)
        self.verticalLayout.addWidget(self.topContainerFrame)
        self.bottomContainerFrame = QtWidgets.QFrame(self.centralwidget)
        self.bottomContainerFrame.setStyleSheet("background-color: #fff;")
        self.bottomContainerFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.bottomContainerFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.bottomContainerFrame.setObjectName("bottomContainerFrame")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.bottomContainerFrame)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.micComboBox = QtWidgets.QComboBox(self.bottomContainerFrame)
        self.micComboBox.setStyleSheet("QComboBox#micComboBox {\n"
"    border: 1px solid #D9DEE2;\n"
"    border-radius: 5px;\n"
"    padding: 3px;\n"
"    padding-right: 20px; /* Make room for the arrow */\n"
"    padding-left: 10px;\n"
"    background-color: white;\n"
"    color: #333333;\n"
"    font-style: bold;\n"
"     font-size: 14px; \n"
"\n"
"}\n"
"\n"
"QComboBox#micComboBox::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    width: 20px;\n"
"    border-left-width: 1px;\n"
"    border-left-color: #D9DEE2;\n"
"    border-left-style: solid;\n"
"    border-top-right-radius: 5px;\n"
"    border-bottom-right-radius: 5px;\n"
"}\n"
"\n"
"QComboBox#micComboBox::down-arrow {\n"
"    image: url(:/icons/dropdown.svg);\n"
"    width: 10px;\n"
"    height: 10px;\n"
"}\n"
"\n"
"QComboBox#micComboBox QListView {\n"
"    border: 1px solid #D9DEE2;\n"
"    border-radius: 5px;\n"
"    background-color: white;\n"
"    outline: 0;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QComboBox#micComboBox QListView::item {\n"
"    padding: 10px 5px;\n"
"    color: black;\n"
"    min-height: 30px; /* Increased for more space */\n"
"    font-size: 14px; /* Increased font size */\n"
"    margin-bottom: 5px; /* Add space between items */\n"
"}\n"
"\n"
"QComboBox#micComboBox QListView::item:hover {\n"
"    background-color: #F8F8F8; /* Very light background on hover */\n"
"}\n"
"\n"
"QComboBox#micComboBox QListView::item:selected {\n"
"    background-color: #E6E6E6;\n"
"    color: black;\n"
"}\n"
"\n"
"/* Add this to create space after the last item */\n"
"QComboBox#micComboBox QListView::item:last-child {\n"
"    margin-bottom: 0;\n"
"}")
        self.micComboBox.setFrame(True)
        self.micComboBox.setObjectName("micComboBox")
        self.micComboBox.addItem("")
        self.micComboBox.addItem("")
        self.horizontalLayout_4.addWidget(self.micComboBox)
        self.verticalLayout.addWidget(self.bottomContainerFrame)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Voice Recorder"))
        self.recordPushButton.setText(_translate("MainWindow", " Start"))
        self.timeQLabel.setText(_translate("MainWindow", "00:00"))
        self.micComboBox.setItemText(0, _translate("MainWindow", "Realtek microphone 1"))
        self.micComboBox.setItemText(1, _translate("MainWindow", "Raser Lvithan"))
import icon_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
